name: Run Celery Worker

on:
  schedule:
    - cron: '12 12 * * 1,3,5' # Runs every Monday, Wednesday, and Friday at 12:12 PM UTC
  workflow_dispatch:

jobs:
  celery-worker:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove unnecessary files
        run: rm -rf invoice-frontend      

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install redis celery

      - name: Run Celery worker
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          REGION_NAME: ${{ secrets.REGION_NAME }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REDIS_BROKER_URL: ${{ secrets.REDIS_BROKER_URL }}

          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          celery -A Celery.celery_worker worker --concurrency=3